### ISSUE TITLE
ReplayClient doesn't respect retries

### ISSUE THREAD

**Issue by ckdarby** [EloGank/lol-replay-downloader-cli#3] opened 2015-11-07 00:47 UTC
Throws an exception before doing the three attempts.

```text

[06-Nov-2015 19:39:51 America/New_York] exception 'Buzz\Exception\RequestException' with message 'file_get_contents(http://66.151.33.19/observer-mode/rest/consumer/getLastChunkInfo/BR1/644504019/7/token): failed to open stream: HTTP request failed! ' in /home/gamerbet/lol-replay-downloader-cli/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php:28
Stack trace:
#0 /home/gamerbet/lol-replay-downloader-cli/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(130): Buzz\Client\FileGetContents->send(Object(Buzz\Message\Request), Object(Buzz\Message\Response))
#1 /home/gamerbet/lol-replay-downloader-cli/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(82): Buzz\Browser->send(Object(Buzz\Message\Request))
#2 /home/gamerbet/lol-replay-downloader-cli/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(31): Buzz\Browser->call('66.151.33.19:80...', 'GET', Array)
#3 /home/gamerbet/lol-replay-downloader-cli/vendor/elogank/lol-replay-downloader/src/EloGank/Replay/Downloader/Client/ReplayClient.php(103): Buzz\Browser->get('66.151.33.19:80...')
#4 /home/gamerbet/lol-replay-downloader-cli/vendor/elogank/lol-replay-downloader/src/EloGank/Replay/Downloader/ReplayDownloader.php(350): EloGank\Replay\Downloader\Client\ReplayClient->getLastChunkInfo('BR1', '644504019', 7)
#5 /home/gamerbet/lol-replay-downloader-cli/vendor/elogank/lol-replay-downloader/src/EloGank/Replay/Downloader/ReplayDownloader.php(538): EloGank\Replay\Downloader\ReplayDownloader->getLastChunkInfos(Object(EloGank\Replay\Replay), 7)
#6 /home/gamerbet/lol-replay-downloader-cli/vendor/elogank/lol-replay-downloader/src/EloGank/Replay/Downloader/ReplayDownloader.php(171): EloGank\Replay\Downloader\ReplayDownloader->downloadCurrentData(Object(EloGank\Replay\Replay), Object(EloGank\Replay\Command\Output\ConsoleOutput))
#7 /home/gamerbet/lol-replay-downloader-cli/vendor/elogank/lol-replay-downloader/src/EloGank/Replay/Downloader/ReplayDownloader.php(106): EloGank\Replay\Downloader\ReplayDownloader->doDownload('BR1', '644504019', '2wimKj03lioTkmJ...', Object(EloGank\Replay\Command\Output\ConsoleOutput))
#8 /home/gamerbet/lol-replay-downloader-cli/src/EloGank/Replay/Command/ReplayDownloadCommand.php(100): EloGank\Replay\Downloader\ReplayDownloader->download('BR1', '644504019', '2wimKj03lioTkmJ...', Object(EloGank\Replay\Command\Output\ConsoleOutput), true)
#9 /home/gamerbet/lol-replay-downloader-cli/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): EloGank\Replay\Command\ReplayDownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/gamerbet/lol-replay-downloader-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/gamerbet/lol-replay-downloader-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(EloGank\Replay\Command\ReplayDownloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/gamerbet/lol-replay-downloader-cli/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/gamerbet/lol-replay-downloader-cli/console(33): Symfony\Component\Console\Application->run()
#14 {main}
```

**Comment by Divi** [comment] 2015-11-07 00:58
Weird, maybe your connection dropped at this moment. I'll check this out tomorrow :)

Thanks.

**Comment by Divi** [comment] 2015-11-07 01:08
The issue seems to be linked with #4.
I close it, feel free to reopen it if the issue occures again.

**Comment by Divi** [comment] 2015-11-07 10:03
@ckdarby The error message means that the URL is not reachable from your server.
Have you tried to cURL the URL manually ?

**Comment by ckdarby** [comment] 2015-11-08 23:38
@Divi Every time I get the error I do a wget on the url and have no issue retrieving it.

**Comment by Divi** [comment] 2015-11-08 23:46
Seems strange. can you try with `file_get_contents` function please ?
I tested locally and it works. Do you have any rules on your iptables/firewall ?

**Comment by ckdarby** [comment] 2015-11-08 23:50
Stock Ubuntu, no iptables/firewall. I think we're making so many requests
Riot might refuse one on their end.

Either way I was assuming the replay downloader should respect the 3
attempts before onFailure().



Sincerely,
Cory Darby
Phone: 1-866-832-2782 || Twitter: ckdarby

**Comment by Divi** [comment] 2015-11-08 23:55
Sure, the issue is real and I'll fix it. But it won't fix your problem.
I don't think Riot has this kind of configuration about max connection attemp.

You should try the domain and not the resolved IP : spectator.br.lol.riotgames.com:80

**Comment by Divi** [comment] 2015-11-11 13:18
Downloader will now catch RequestException and will retry like a timeout. See https://github.com/EloGank/lol-replay-downloader/commit/23271230a7f823b1757f0e2a9f60d1a7d4fa95d6

Like I said, your `failed to open stream: HTTP request failed!` won't be fixed by magic. You seem to have a connection issue.

Thanks @ckdarby :+1:

**Closed by Divi** 2015-11-11 13:18 UTC
Labels: bug
